#!/bin/bash
echo "Author :ANAZ"
echo "Scripted by DevAnaZ"
echo "Orgin Repository: https://github.com/developeranaz/RCLONE-SERVE-INDEX"
rclone version
curl -L $CONFIG_IN_URL >/rclone.conf
rclone listremotes
echo "$template" >.template
cat .template |sed 's/dark/0/g' |sed 's/light/1/g' >.darklight
if [ $(cat .darklight) -eq 0 ]
then
    echo "Theme:Dark"
    thetheme="/usr/bin/.con/1.html"
else
    echo "Theme:Light"
    thetheme="/usr/bin/.con/0.html"
fi
#rc auth
echo "$indexauthentication" >.yesno
cat .yesno |sed 's/false/0/g' |sed 's/true/1/g' >.auth
if [ $(cat .auth) -eq 0 ]
then
    echo "no password, hence unautheticated index"
    theindexpassword=''
    theindexusername=''
else
    echo "oh! password, hence authenticated index"
    theindexpassword="$INDEXpassword"
    theindexusername="$INDEXusername"
fi
##############################################################################

echo "$webdav $WEBDAV $WebDav $Webdav" >/webdav
if grep -i "true\|rue\|RUE\|TRUE\|T\|OK\|ok\|on\|ON" /webdav
then
    echo "found"
    
    rclone serve webdav $(rclone listremotes --config=/rclone.conf |head -1 |grep ':') --config=/rclone.conf --user="$theindexusername" --pass="$theindexpassword"  --config=/rclone.conf
else
    echo "not"
    rclone rcd --rc-serve --rc-addr=0.0.0.0:$PORT --rc-pass="$theindexpassword" --rc-user="$theindexusername" --rc-template="$thetheme" --config=/rclone.conf
fi


